#!/bin/bash
#
# Submit new operator version against rancher/charts

set -ue

PREV_OPERATOR_VERSION="$1"   # e.g. 1.1.0-rc3
NEW_OPERATOR_VERSION="$2"
PREV_CHART_VERSION="$3"   # e.g. 101.2.0
NEW_CHART_VERSION="$4"
REPLACE="$5"              # remove previous version if `true`, otherwise add new

OPERATOR="${OPERATOR:-eks-operator}"

if [ -z "${GITHUB_WORKSPACE:-}" ]; then
    CHARTS_DIR="$(dirname -- "$0")/../../../charts"
else
    CHARTS_DIR="${GITHUB_WORKSPACE}/charts"
fi

pushd "${CHARTS_DIR}" > /dev/null

if [ ! -e ~/.gitconfig ]; then
    git config --global user.name "highlander-ci-bot"
    git config --global user.email highlander-ci@proton.me
fi

if [ ! -f bin/charts-build-scripts ]; then
    make pull-scripts
fi

find ./packages/rancher-${OPERATOR}/ -type f -exec sed -i -e "s/${PREV_OPERATOR_VERSION}/${NEW_OPERATOR_VERSION}/g" {} \;
find ./packages/rancher-${OPERATOR}/ -type f -exec sed -i -e "s/version: ${PREV_CHART_VERSION}/version: ${NEW_CHART_VERSION}/g" {} \;
find ./packages/rancher-${OPERATOR}/ -type f -exec sed -i -e "/doNotRelease: false/d" {} \;

if [ "${REPLACE}" == "true" ] && grep -q "rancher-${OPERATOR}:" release.yaml; then
    sed -i -e "s/${PREV_CHART_VERSION}+up${PREV_OPERATOR_VERSION}/${NEW_CHART_VERSION}+up${NEW_OPERATOR_VERSION}/g" release.yaml
else
    if grep -q "rancher-${OPERATOR}:" release.yaml; then
        sed -i -e "s/${PREV_CHART_VERSION}+up${PREV_OPERATOR_VERSION}/${PREV_CHART_VERSION}+up${PREV_OPERATOR_VERSION}\n  - ${NEW_CHART_VERSION}+up${NEW_OPERATOR_VERSION}/g" release.yaml
    else
        cat <<< "
rancher-${OPERATOR}:
- ${PREV_CHART_VERSION}+up${PREV_OPERATOR_VERSION}
- ${NEW_CHART_VERSION}+up${NEW_OPERATOR_VERSION}
rancher-${OPERATOR}-crd:
- ${PREV_CHART_VERSION}+up${PREV_OPERATOR_VERSION}
- ${NEW_CHART_VERSION}+up${NEW_OPERATOR_VERSION}" >> release.yaml
    # remove empty line above rancher-${OPERATOR}
    sed -i -z -e  "s/[[:space:]]*\nrancher-${OPERATOR}:/\nrancher-${OPERATOR}:/g" release.yaml
    fi
fi

git add packages/rancher-${OPERATOR} release.yaml
git commit -m "Updating to Operator v${NEW_OPERATOR_VERSION}"

if [ "${REPLACE}" == "true" ]; then
for i in rancher-${OPERATOR} rancher-${OPERATOR}-crd; do CHART=$i VERSION=${PREV_CHART_VERSION}+up${PREV_OPERATOR_VERSION} make remove; done
fi

PACKAGE=rancher-${OPERATOR} make charts
git add assets/rancher-${OPERATOR}* charts/rancher-${OPERATOR}* index.yaml
git commit -m "Autogenerated changes for Operator v${NEW_OPERATOR_VERSION}"

popd > /dev/null
