// Code generated by MockGen. DO NOT EDIT.
// Source: ../cloudformation.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	reflect "reflect"

	cloudformation "github.com/aws/aws-sdk-go/service/cloudformation"
	gomock "github.com/golang/mock/gomock"
)

// MockCloudFormationServiceInterface is a mock of CloudFormationServiceInterface interface.
type MockCloudFormationServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCloudFormationServiceInterfaceMockRecorder
}

// MockCloudFormationServiceInterfaceMockRecorder is the mock recorder for MockCloudFormationServiceInterface.
type MockCloudFormationServiceInterfaceMockRecorder struct {
	mock *MockCloudFormationServiceInterface
}

// NewMockCloudFormationServiceInterface creates a new mock instance.
func NewMockCloudFormationServiceInterface(ctrl *gomock.Controller) *MockCloudFormationServiceInterface {
	mock := &MockCloudFormationServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCloudFormationServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudFormationServiceInterface) EXPECT() *MockCloudFormationServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateStack mocks base method.
func (m *MockCloudFormationServiceInterface) CreateStack(input *cloudformation.CreateStackInput) (*cloudformation.CreateStackOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStack", input)
	ret0, _ := ret[0].(*cloudformation.CreateStackOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStack indicates an expected call of CreateStack.
func (mr *MockCloudFormationServiceInterfaceMockRecorder) CreateStack(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStack", reflect.TypeOf((*MockCloudFormationServiceInterface)(nil).CreateStack), input)
}

// DeleteStack mocks base method.
func (m *MockCloudFormationServiceInterface) DeleteStack(input *cloudformation.DeleteStackInput) (*cloudformation.DeleteStackOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStack", input)
	ret0, _ := ret[0].(*cloudformation.DeleteStackOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteStack indicates an expected call of DeleteStack.
func (mr *MockCloudFormationServiceInterfaceMockRecorder) DeleteStack(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStack", reflect.TypeOf((*MockCloudFormationServiceInterface)(nil).DeleteStack), input)
}

// DescribeStackEvents mocks base method.
func (m *MockCloudFormationServiceInterface) DescribeStackEvents(input *cloudformation.DescribeStackEventsInput) (*cloudformation.DescribeStackEventsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeStackEvents", input)
	ret0, _ := ret[0].(*cloudformation.DescribeStackEventsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeStackEvents indicates an expected call of DescribeStackEvents.
func (mr *MockCloudFormationServiceInterfaceMockRecorder) DescribeStackEvents(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeStackEvents", reflect.TypeOf((*MockCloudFormationServiceInterface)(nil).DescribeStackEvents), input)
}

// DescribeStacks mocks base method.
func (m *MockCloudFormationServiceInterface) DescribeStacks(input *cloudformation.DescribeStacksInput) (*cloudformation.DescribeStacksOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeStacks", input)
	ret0, _ := ret[0].(*cloudformation.DescribeStacksOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeStacks indicates an expected call of DescribeStacks.
func (mr *MockCloudFormationServiceInterfaceMockRecorder) DescribeStacks(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeStacks", reflect.TypeOf((*MockCloudFormationServiceInterface)(nil).DescribeStacks), input)
}
