// Code generated by MockGen. DO NOT EDIT.
// Source: ../sts.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"

	sts "github.com/aws/aws-sdk-go-v2/service/sts"
	gomock "github.com/golang/mock/gomock"
)

// MockSTSServiceInterface is a mock of STSServiceInterface interface.
type MockSTSServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSTSServiceInterfaceMockRecorder
}

// MockSTSServiceInterfaceMockRecorder is the mock recorder for MockSTSServiceInterface.
type MockSTSServiceInterfaceMockRecorder struct {
	mock *MockSTSServiceInterface
}

// NewMockSTSServiceInterface creates a new mock instance.
func NewMockSTSServiceInterface(ctrl *gomock.Controller) *MockSTSServiceInterface {
	mock := &MockSTSServiceInterface{ctrl: ctrl}
	mock.recorder = &MockSTSServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSTSServiceInterface) EXPECT() *MockSTSServiceInterfaceMockRecorder {
	return m.recorder
}

// GetCallerIdentity mocks base method.
func (m *MockSTSServiceInterface) GetCallerIdentity(ctx context.Context, input *sts.GetCallerIdentityInput) (*sts.GetCallerIdentityOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCallerIdentity", ctx, input)
	ret0, _ := ret[0].(*sts.GetCallerIdentityOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCallerIdentity indicates an expected call of GetCallerIdentity.
func (mr *MockSTSServiceInterfaceMockRecorder) GetCallerIdentity(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCallerIdentity", reflect.TypeOf((*MockSTSServiceInterface)(nil).GetCallerIdentity), ctx, input)
}
