apiVersion: eks.cattle.io/v1
kind: EKSClusterConfig
metadata:
  name: my-cluster
spec:
  kubernetesVersion: "1.15"
  publicAccess: true
  privateAccess: true
  amazonCredentialSecr: "cattle-global-data:cc-zzzz"
  displayName: "my-cluster"
  region: "us-east-2"
  loggingTypes: ["audit"]
  nodeGroups:
  - nodegroupName: "mycluster-ng1"
    instanceType: "t3.medium"
    desiredSize: 1
    maxSize: 2
    minSize: 1
