#!/bin/bash

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
if [ "$(uname)" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static -s"
fi
CGO_ENABLED=0 go build -ldflags "$OTHER_LINKFLAGS" -o bin/eks-operator