name: Go API Diff
on: 
  pull_request:
jobs:
  go-apidiff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
      with:
        go-version: 1.24.x
    - name: Generate API diff
      run: make apidiff
