name: Unit tests
on:
  pull_request:
  push:
    branches: [ "main", "release-v*" ]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
    - name: Install Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
      with:
        go-version: 1.25.x
    - name: Run tests
      run: |
        make test
